# -*- coding: utf-8 -*-
"""Griffin_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Mxe9fzpi9CCp5iy3WLnvyzT1HrkJPhG
"""

# 모든 데이터 다 불러오기
import os
import json

# 팀: Griffin
gri_dic = {} # 딕셔너리
gri_key = [] # 리스트

for root, dirs, files in os.walk(os.path.join('data','Griffin')):
    for fname in files:
      if fname.endswith(".json"): #끝이 ".json"로 끝나는 경우
        full_fname = os.path.join(root, fname)
        gri_key.append(fname)
        
        with open(full_fname) as json_file:
          json_data = json.load(json_file)
          gri_dic[fname] = json_data
        
gri_key.sort() #  리스트 오름차순 정렬

import datetime
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

gri_total_likes = []
gri_convert_time = []
gri_length = []

for name in gri_key:
  values = gri_dic[name]['results'][0]['series'][0]['values']
  
  # total_likes: 주어진 데이터의 2번째 value들
  length = len(values)  
  gri_length.append(length)

  for i in range(0,length):
      gri_total_likes.append(values[i][2])
  
  # conver_times: 주어진 데이터의 0번째 value들
  for i in range(0, length):
      gri_convert_time.append(datetime.datetime.strptime(values[i][0][:19],"%Y-%m-%dT%H:%M:%S"))

# total_likes2 = total_likes의 차이값들(하루 단위)
gri_total_likes2 = []
gri_differences = []
gri_date = []
for name in gri_key:
  values = gri_dic[name]['results'][0]['series'][0]['values']
  length = len(values)  
  gri_total_likes2.append(values[length-1][2])
  gri_date.append(datetime.datetime.strptime(values[0][0][:10],"%Y-%m-%d"))    

for i in range(0,len(gri_date)-1):
  gri_differences.append(gri_total_likes2[i+1]-gri_total_likes2[i])

# 시간에 따른 total likes 값들 시각화
fig = plt.figure()
ax = plt.subplot(1, 1, 1)

plt.plot(gri_convert_time, gri_total_likes)
#plt.rcParams["figure.figsize"] = (22,5)
plt.title('Griffin')
plt.xlabel('Time')
plt.ylabel('Total Likes')
for label in ax.xaxis.get_ticklabels() :
    label.set_rotation(45)
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
plt.show()

# 시간에 따른 total likes 차이값들 시각화(막대그래프)
fig = plt.figure()
ax = plt.subplot(1, 1, 1)

bar_graph = plt.bar(gri_date[1:], gri_differences, align='edge', edgecolor='black')
plt.title('Griffin')
plt.xlabel('Date')
plt.ylabel('Difference of Likes')
for label in ax.xaxis.get_ticklabels() :
    label.set_rotation(45)
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
ax.set_axisbelow(True)
plt.grid(True)
plt.show()

# 좋아요 증가율 구하기
import numpy as np

average = []
sum = 0

for i in gri_length:
  sum = sum+i
  avg = (gri_total_likes[sum-1] - gri_total_likes[sum-i])/(gri_convert_time[sum-1] - gri_convert_time[sum-i]).seconds*60
  average.append(avg)

gri_avg = np.mean(average)
print("Griffin 좋아요 증가율:", gri_avg)