# -*- coding: utf-8 -*-
"""KINGZONEDX_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LPYlw6GeDcZL_y2BK2AkE6RXC3Fu_Gtq
"""

# 모든 데이터 다 불러오기
import os
import json

# 팀: KINGZONEDX
king_dic = {} # 딕셔너리
king_key = [] # 리스트

for root, dirs, files in os.walk(os.path.join('data','KINGZONEDX')):
    for fname in files:
      if fname.endswith(".json"): #끝이 ".json"로 끝나는 경우
        full_fname = os.path.join(root, fname)
        king_key.append(fname)
        
        with open(full_fname) as json_file:
          json_data = json.load(json_file)
          king_dic[fname] = json_data

king_key.sort() #  리스트 오름차순 정렬

import datetime
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

king_total_likes = []
king_convert_time = []
king_length = []

for name in king_key:
  values = king_dic[name]['results'][0]['series'][0]['values']
  
  # total_likes: 주어진 데이터의 2번째 value들
  length = len(values)
  king_length.append(length)

  for i in range(0,length):
      king_total_likes.append(values[i][2])
  
  # conver_times: 주어진 데이터의 0번째 value들
  for i in range(0, length):
      king_convert_time.append(datetime.datetime.strptime(values[i][0][:19],"%Y-%m-%dT%H:%M:%S"))

# total_likes2 = total_likes의 차이값들(하루 단위)
king_total_likes2 = []
king_differences = []
king_date = []
for name in king_key:
  values = king_dic[name]['results'][0]['series'][0]['values']
  length = len(values)  
  king_total_likes2.append(values[length-1][2])
  king_date.append(datetime.datetime.strptime(values[0][0][:10],"%Y-%m-%d"))    

for i in range(0,len(king_date)-1):
  king_differences.append(king_total_likes2[i+1]-king_total_likes2[i])

# 시간에 따른 total likes 값들 시각화
fig = plt.figure()
ax = plt.subplot(1, 1, 1)

plt.plot(king_convert_time, king_total_likes)
#plt.rcParams["figure.figsize"] = (22,5)
plt.title('KINGZONEDX')
plt.xlabel('Time')
plt.ylabel('Total Likes')
for label in ax.xaxis.get_ticklabels() :
    label.set_rotation(45)
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
plt.show()

# 시간에 따른 total likes 차이값들 시각화(막대그래프)
fig = plt.figure()
ax = plt.subplot(1, 1, 1)

bar_graph = plt.bar(king_date[1:], king_differences, align='edge', edgecolor='black')
plt.title('KINGZONEDX')
plt.xlabel('Date')
plt.ylabel('Difference of Likes')
for label in ax.xaxis.get_ticklabels() :
    label.set_rotation(45)
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
ax.set_axisbelow(True)
plt.grid(True)
plt.show()

# 좋아요 증가율 구하기
import numpy as np

average = []
sum = 0

for i in king_length:
  sum = sum+i
  avg = (king_total_likes[sum-1] - king_total_likes[sum-i])/(king_convert_time[sum-1] - king_convert_time[sum-i]).seconds*60
  average.append(avg)

king_avg = np.mean(average)
print("KINGZONEDX 좋아요 증가율:",king_avg)